# Generated by Django 4.1 on 2022-09-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('singer', models.CharField(max_length=100)),
                ('chord', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Chords',
        ),
    ]
